apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: {{ required "Postgres port has to be defined" .Values.postgres_port }}
      targetPort: {{ required "Postgres port has to be defined" .Values.postgres_port }}
