apiVersion: v1
kind: Service
metadata:
  name: postgres-external
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: postgres
  ports:
    - name: postgres-external
      port: {{ required "Postgres port has to be defined" .Values.postgres_port }}
      targetPort: {{ required "Postgres port has to be defined" .Values.postgres_port }}
      nodePort: 30030
  type: NodePort
