# Keep in mind, when deploying this you would have to copy the secret to the ingress-nginx namespace.
# kubectl get secret reduced.to-tls -n cert-manager -o yaml | sed 's/namespace: cert-manager/namespace: default/' | kubectl apply -f -
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: reduced.to
spec:
  secretName: reduced.to-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - reduced.to
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - reduced.to
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
