apiVersion: v1
kind: ConfigMap
metadata:
  name: reduced-configmap
data:
  # General
  BACKEND_APP_PORT: '3000'
  FRONTEND_APP_PORT: '5000'
  TRACKER_APP_PORT: '3001'
  NODE_ENV: 'production'

  # RATE LIMIT
  RATE_LIMIT_TTL: '60'
  RATE_LIMIT_COUNT: '100'

  # PADDLE - (Payment Gateway)
  PADDLE_ENABLE: 'false'
  PADDLE_WEBHOOK_KEY: 'pld_test_webhook_key'
  PADDLE_SECRET_KEY: 'secret_key'

  # LOGGER
  LOGGER_CONSOLE_THRESHOLD: 'INFO' # DEBUG, INFO, WARN, ERROR, FATAL

  # FRONTEND
  DOMAIN: 'reduced.to'
  PUBLIC_PADDLE_KEY: 'test_public_key'
  CLIENTSIDE_API_DOMAIN: 'https://reduced.to' # Use this variable while making client-side API calls
  API_DOMAIN: 'http://backend-service:3000' # Use this variable while making server-side API calls
  STORAGE_DOMAIN: 'Get it from https://cloud.digitalocean.com/spaces'

  # DATABASE
  POSTGRES_PORT: '5432'
  POSTGRES_DB: 'reduced_to_db'
  POSTGRES_USER: 'postgres'
  POSTGRES_PASSWORD: 'postgres'
  DATABASE_URL: 'postgresql://postgres:postgres@postgres-service:5432/reduced_to_db'

  # REDIS
  REDIS_ENABLE: 'false'
  REDIS_HOST: 'redis-service'
  REDIS_PORT: '6379'
  REDIS_PASSWORD: 'password'
  REDIS_TTL: '1800000' # 30 minutes in ms (default TTL)

  # NOVU - You don't need this when running locally (just verify your email from the database)
  NOVU_API_KEY: 'Get it from https://novu.co/'

  # KAFKA (Used for analytics)
  KAFKA_ENABLE: 'false'
  KAFKA_BROKER: ''
  KAFKA_USERNAME: ''
  KAFKA_PASSWORD: ''

  # AUTH
  AUTH_JWT_ACCESS_SECRET: 'abc1234'
  AUTH_JWT_REFRESH_SECRET: 'abc1234'
  AUTH_GOOGLE_CLIENT_ID: 'Get it from https://console.cloud.google.com/apis/credentials'
  AUTH_GOOGLE_CLIENT_SECRET: 'Get it from https://console.cloud.google.com/apis/credentials'

  # SAFE URL
  SAFE_URL_GOOGLE_SAFE_BROWSING_API_KEY: 'Get it from https://console.cloud.google.com/apis/credentials'
  SAFE_URL_ENABLE: 'false'

  # TRACKER
  TRACKER_STATS_TOPIC_NAME: 'stats'

  # STORAGE
  STORAGE_ENABLE: 'false'
  STORAGE_ENDPOINT: 'Get it from https://cloud.digitalocean.com/spaces'
  STORAGE_ACCESS_KEY: 'Get it from https://cloud.digitalocean.com/spaces'
  STORAGE_SECRET_KEY: 'Get it from https://cloud.digitalocean.com/spaces'
  STORAGE_BUCKET_NAME: 'Get it from https://cloud.digitalocean.com/spaces'
