# Make sure to enable proxy protocol in the ingress controller:
# For those who use DigitalOcean, https://docs.digitalocean.com/support/how-do-i-enable-proxy-protocol-when-my-load-balancer-sends-requests-to-the-nginx-ingress-controller/
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true' # Enforce HTTPS
  labels:
    app: reduced
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - reduced.to
        - www.reduced.to
      secretName: letsencrypt-prod # Name of the secret containing the certificate
  rules:
    - host: reduced.to
      http: &http
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 5000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 3000
    - host: www.reduced.to
      http: *http
