apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: {{ required "Frontend port has to be defined" .Values.frontend.port }}
      targetPort: {{ required "Frontend port has to be defined" .Values.frontend.port }}
  type: 'LoadBalancer'
