apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reduced-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ required "TLS issuer has to be defined" .Values.tls.issuer }}
    kubernetes.io/ingress.class: 'nginx'
  labels:
    app: reduced
spec:
  ingressClassName: NginxIngressController
  tls:
    - hosts:
        - {{ .Values.shared_configmap.DOMAIN }}
      secretName: {{ required "TLS secret has to be defined" .Values.tls.secret_name }}
  rules:
    - host: {{ .Values.shared_configmap.DOMAIN }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 5000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 3000
