apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  annotations:
    # force policy will ensure that deployment is updated
    # even when tag is unchanged (latest remains)
    keel.sh/policy: force
    keel.sh/trigger: poll # <-- actively query registry, otherwise defaults to webhooks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/origranot/reduced.to/backend:master
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: reduced-configmap
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: '256Mi'
              cpu: '100m'
            limits:
              memory: '1024Mi'
              cpu: '500m'
