apiVersion: v1
kind: Service
metadata:
  name: postgres-external
spec:
  selector:
    app: postgres
  ports:
    - name: postgres-external
      port: 5432
      targetPort: 5432
      nodePort: 30030
  type: NodePort
