apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: {{ required "Redis port has to be defined" .Values.redis_port }}
      targetPort: {{ required "Redis port has to be defined" .Values.redis_port }}
