# This is a basic workflow to help you get started with Actions

name: main workflow

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      stack:
        required: true
        type: string
      securityScan:
        required: true
        type: boolean

jobs:
  preperation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
