name: URL-Shortener CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  lint-package:
    name: Lint Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Install NPM Dependencies
        run: npm install

      - name: Prettier Check
        if: ${{ always() }}
        run: npm run fmt
