name: '[CI] Release version'
on:
  push:
    branches:
      - AddingCI
  workflow_dispatch:

jobs:
  buildDockerAndPush:
    name: Release
    uses: ./.github/workflows/bla.yml
    with:
      stack: 'node'
      securityScan: true
