# This is a basic workflow to help you get started with Actions

name: Release New Version

# Controls when the workflow will run
on:
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout

jobs:
  preperation:
    uses: devcon-devops-as-a-service/actions/.github/workflows/mainworkflow.yml@main
    secrets: inherit
    with:
      stack: nx
      securityscan: true
      appName: reduced-to
